# Generated by Django 5.1.1 on 2025-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColaboradorPonto',
            fields=[
                ('cpf', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
            ],
            options={
                'verbose_name': 'Colaborador Ponto (Cache)',
                'verbose_name_plural': 'Colaboradores Ponto (Cache)',
            },
        ),
        migrations.CreateModel(
            name='LogAtualizacaoCPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bitrix', models.IntegerField(verbose_name='ID Bitrix')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=20, verbose_name='CPF Atualizado')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioBitrix',
            fields=[
                ('id_bitrix', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Bitrix')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Bitrix')),
            ],
            options={
                'verbose_name': 'Usuário Bitrix (Cache)',
                'verbose_name_plural': 'Usuários Bitrix (Cache)',
            },
        ),
    ]
