# Generated by Django 5.1.1 on 2025-12-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacao_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCPFCheck',
            fields=[
                ('id_bitrix', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Bitrix')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Bitrix')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('OK', 'Coincidente'), ('SEM_MATCH', 'Sem match'), ('DUPLICADO', 'Duplicado')], max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Check de Match (Ponto x Bitrix)',
                'verbose_name_plural': 'Checks de Match (Ponto x Bitrix)',
                'ordering': ['status', 'nome'],
            },
        ),
    ]
