# Generated by Django 5.1.1 on 2025-12-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sincronizacao_user', '0002_matchcpfcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchcpfcheck',
            options={'ordering': ['status', 'nome'], 'verbose_name': 'Check Match (Ponto x Bitrix)', 'verbose_name_plural': 'Checks Match (Ponto x Bitrix)'},
        ),
    ]
