# Generated by Django 5.1.1 on 2025-10-26 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CcontrolWebUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('fonte_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DominioAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('fonte_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GesttaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('fonte_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('success', 'success'), ('error', 'error')], default='running', max_length=20)),
                ('mensagem', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitrixUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('user_dominio', models.CharField(blank=True, max_length=255, null=True)),
                ('user_local', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('fonte_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['nome_completo'], name='core_bitrix_nome_co_057160_idx'), models.Index(fields=['user_dominio'], name='core_bitrix_user_do_f80664_idx'), models.Index(fields=['user_local'], name='core_bitrix_user_lo_5ce18e_idx'), models.Index(fields=['email'], name='core_bitrix_email_22bcd7_idx')],
            },
        ),
        migrations.CreateModel(
            name='N8nContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('fonte_raw', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['nome'], name='core_n8ncon_nome_667980_idx'), models.Index(fields=['email'], name='core_n8ncon_email_f0d905_idx')],
                'unique_together': {('nome', 'email')},
            },
        ),
        migrations.CreateModel(
            name='SyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonte', models.CharField(choices=[('BITRIX', 'BITRIX'), ('N8N', 'N8N'), ('GESTTA', 'GESTTA'), ('DOMINIO', 'DOMINIO'), ('CCONTROLWEB', 'CCONTROLWEB')], max_length=20)),
                ('lidos', models.IntegerField(default=0)),
                ('gravados', models.IntegerField(default=0)),
                ('ignorados', models.IntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('sync_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
