# Generated by Django 5.1.1 on 2025-10-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominioaccount',
            name='id_externo',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dominioaccount',
            name='fonte_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dominioaccount',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
