# Generated by Django 5.1.1 on 2025-10-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dominioaccount_id_externo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fonte', models.CharField(choices=[('BITRIX', 'BITRIX'), ('N8N', 'N8N'), ('GESTTA', 'GESTTA'), ('DOMINIO', 'DOMINIO'), ('CCONTROLWEB', 'CCONTROLWEB')], max_length=20)),
                ('lidos', models.IntegerField(default=0)),
                ('gravados', models.IntegerField(default=0)),
                ('ignorados', models.IntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.syncrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SyncItem',
        ),
    ]
