# Generated by Django 5.1.1 on 2025-10-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_syncdetail_delete_syncitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitrixuser',
            name='nome_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='bitrixuser',
            index=models.Index(fields=['nome_user'], name='core_bitrix_nome_us_ed8d5e_idx'),
        ),
    ]
