# Generated by Django 5.1.1 on 2025-10-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bitrixuser_nome_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='N8nContact',
            new_name='PontoContact',
        ),
        migrations.RenameIndex(
            model_name='pontocontact',
            new_name='core_pontoc_nome_689dfd_idx',
            old_name='core_n8ncon_nome_667980_idx',
        ),
        migrations.RenameIndex(
            model_name='pontocontact',
            new_name='core_pontoc_email_542023_idx',
            old_name='core_n8ncon_email_f0d905_idx',
        ),
        migrations.AlterField(
            model_name='syncdetail',
            name='fonte',
            field=models.CharField(choices=[('BITRIX', 'BITRIX'), ('Ponto', 'Ponto'), ('GESTTA', 'GESTTA'), ('DOMINIO', 'DOMINIO'), ('CCONTROLWEB', 'CCONTROLWEB')], max_length=20),
        ),
    ]
