# Generated by Django 5.1.1 on 2025-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_n8ncontact_pontocontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaoLogicaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_funcionario', models.IntegerField(unique=True, verbose_name='Cód. Funcionário')),
                ('nome_funcionario', models.CharField(max_length=255, verbose_name='Nome Funcionário')),
                ('dep_funcionario', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
