# Generated by Django 5.1.1 on 2025-12-19 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_visaologicauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaologicauser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visaologicauser',
            name='fonte_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='syncdetail',
            name='fonte',
            field=models.CharField(choices=[('BITRIX', 'BITRIX'), ('Ponto', 'Ponto'), ('GESTTA', 'GESTTA'), ('DOMINIO', 'DOMINIO'), ('CCONTROLWEB', 'CCONTROLWEB'), ('VISAOLOGICA', 'VISAOLOGICA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visaologicauser',
            name='codigo_funcionario',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='visaologicauser',
            name='dep_funcionario',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visaologicauser',
            name='nome_funcionario',
            field=models.CharField(max_length=255),
        ),
    ]
