# Generated by Django 5.1.1 on 2025-12-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visaologicauser_created_at_visaologicauser_fonte_raw_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pontocontact',
            name='core_pontoc_nome_689dfd_idx',
        ),
        migrations.RemoveIndex(
            model_name='pontocontact',
            name='core_pontoc_email_542023_idx',
        ),
        migrations.RenameField(
            model_name='pontocontact',
            old_name='email',
            new_name='nome_completo',
        ),
        migrations.RenameField(
            model_name='pontocontact',
            old_name='nome',
            new_name='status_ponto',
        ),
        migrations.AlterUniqueTogether(
            name='pontocontact',
            unique_together=set(),
        ),
    ]
